export interface FlexProps {
    ref?: any
    color?: any
    style?: any
    justifyContent?:
        | 'flex-start'
        | 'flex-end'
        | 'center'
        | 'space-between'
        | 'space-around'
        | 'space-evenly'
        | 'initial'
        | 'inherit'
        | 'unset'
    alignItems?:
        | 'normal'
        | 'stretch'
        | 'start'
        | 'end'
        | 'flex-start'
        | 'flex-end'
        | 'center'
        | 'baseline'
        | 'first baseline'
        | 'last baseline'
        | 'safe cente'
        | 'unsafe center'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    alignContent?:
        | 'normal'
        | 'stretch'
        | 'start'
        | 'end'
        | 'flex-start'
        | 'flex-end'
        | 'center'
        | 'baseline'
        | 'first baseline'
        | 'last baseline'
        | 'space-between'
        | 'space-around	'
        | 'space-evenly'
        | 'safe cente'
        | 'unsafe center'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    direction?:
        | 'row'
        | 'row-reverse'
        | 'column'
        | 'column-reverse'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    display?:
        | 'flex'
        | 'block'
        | 'inline'
        | 'inline-block'
        | 'inline-flex'
        | 'grid'
        | 'inline-grid'
        | 'flow-root'
        | 'none'
        | 'contents'
        | 'block flow'
        | 'inline flow'
        | 'inline flow-root'
        | 'block flex'
        | 'inline flex'
        | 'block grid'
        | 'inline grid'
        | 'block flow-root'
        | 'table'
        | 'table-row'
        | 'list-item'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    wrap?:
        | 'nowrap'
        | 'wrap'
        | 'wrap-reverse'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    order?: number | 'inherit' | 'initial' | 'revert' | 'revert-layer' | 'unset'
    grow?: number | 'inherit' | 'initial' | 'revert' | 'revert-layer' | 'unset'
    shrink?: number | 'inherit' | 'initial' | 'revert' | 'revert-layer' | 'unset'
    basis?:
        | number
        | string
        | 'content'
        | 'max-content'
        | 'min-content'
        | 'fit-content'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    alignSelf?:
        | 'auto'
        | 'normal'
        | 'stretch'
        | 'start'
        | 'end'
        | 'flex-start'
        | 'flex-end'
        | 'self-start'
        | 'self-end'
        | 'center'
        | 'baseline'
        | 'first baseline'
        | 'last baseline'
        | 'safe cente'
        | 'unsafe center'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    width?:
        | string
        | 'max-content'
        | 'min-content'
        | 'auto'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    minWidth?:
        | string
        | 'max-content'
        | 'min-content'
        | 'auto'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    maxWidth?:
        | string
        | 'max-content'
        | 'min-content'
        | 'auto'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    height?:
        | string
        | 'max-content'
        | 'min-content'
        | 'auto'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    minHeight?:
        | string
        | 'max-content'
        | 'min-content'
        | 'auto'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    maxHeight?:
        | string
        | 'max-content'
        | 'min-content'
        | 'auto'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    padding?: string | 'inherit' | 'initial' | 'revert' | 'revert-layer' | 'unset'
    margin?: string | 'inherit' | 'initial' | 'revert' | 'revert-layer' | 'unset'
    overflow?:
        | 'visible'
        | 'hidden'
        | 'clip'
        | 'scroll'
        | 'auto'
        | 'hidden visible'
        | 'inherit'
        | 'initial'
        | 'revert'
        | 'revert-layer'
        | 'unset'
    children?: any
    position?:
        | 'relative'
        | 'fixed'
        | 'inherit'
        | 'initial'
        | 'absolute'
        | 'revert'
        | 'static'
        | 'sticky'
        | 'unset'
    onClick?: (event: any) => void
    className?: string
}
