export const placeholderTranslations: any = {
    ar: 'أدخل اسم المدينة',
    bn: 'একটি শহর লিখুন',
    bg: 'Въведете град',
    zh: '输入城市',
    cs: 'Zadejte město',
    da: 'Indtast en by',
    nl: 'Voer een stad in',
    fi: 'Kirjoita kaupunki',
    fr: 'Entrez une ville',
    de: 'Geben Sie eine Stadt ein',
    el: 'Εισάγετε μια πόλη',
    hi: 'एक शहर लिखें',
    hu: 'Írjon be egy várost',
    it: 'Inserisci una città',
    ja: '都市名を入力してください',
    jv: 'Tulis kota',
    ko: '도시를 입력하세요',
    mr: 'एक शहर लिहा',
    pl: 'Wpisz miasto',
    pt: 'Digite uma cidade',
    pa: 'ਇੱਕ ਸ਼ਹਿਰ ਲਿਖੋ',
    ro: 'Introduceți un oraș',
    ru: 'Введите название города',
    sr: 'Унесите град',
    si: 'නගරයක් ඇතුළු කරන්න',
    sk: 'Zadajte mesto',
    es: 'Ingrese una ciudad',
    sv: 'Skriv in en stad',
    ta: 'ஒரு நகரை உள்ளிடவும்',
    te: 'ఒక నగరం రాయండి',
    tr: 'Bir şehir girin',
    uk: 'Введіть назву міста',
    ur: 'ایک شہر لکھیں',
    vi: 'Nhập tên thành phố',
    zu: 'Faka isifunda',
    us: 'Enter a city',
}

export const languages = [
    { label: '🇦🇺', value: 'ar' },
    { label: '🇧🇩', value: 'bn' },
    { label: '🇧🇬', value: 'bg' },
    { label: '🇨🇳', value: 'zh' },
    { label: '🇨🇿', value: 'cs' },
    { label: '🇩🇰', value: 'da' },
    { label: '🇳🇱', value: 'nl' },
    { label: '🇫🇮', value: 'fi' },
    { label: '🇫🇷', value: 'fr' },
    { label: '🇺🇸', value: 'us' },
    { label: '🇩🇪', value: 'de' },
    { label: '🇬🇷', value: 'el' },
    { label: '🇮🇳', value: 'hi' },
    { label: '🇭🇺', value: 'hu' },
    { label: '🇮🇹', value: 'it' },
    { label: '🇯🇵', value: 'ja' },
    { label: '🇮🇩', value: 'jv' },
    { label: '🇰🇷', value: 'ko' },
    { label: '🇮🇳', value: 'mr' },
    { label: '🇵🇱', value: 'pl' },
    { label: '🇵🇹', value: 'pt' },
    { label: '🇵🇰', value: 'pa' },
    { label: '🇷🇴', value: 'ro' },
    { label: '🇷🇺', value: 'ru' },
    { label: '🇷🇸', value: 'sr' },
    { label: '🇱🇰', value: 'si' },
    { label: '🇸🇰', value: 'sk' },
    { label: '🇪🇸', value: 'es' },
    { label: '🇸🇪', value: 'sv' },
    { label: '🇮🇳', value: 'ta' },
    { label: '🇮🇳', value: 'te' },
    { label: '🇹🇷', value: 'tr' },
    { label: '🇸🇦', value: 'uk' },
    { label: '🇵🇰', value: 'ur' },
    { label: '🇻🇳', value: 'vi' },
    { label: '🇿🇦', value: 'zu' },
]
